### ISSUE TITLE
Bitbake builds fail  on ubuntu 14.04 (Linux Mint 17.1)

### ISSUE THREAD

**Issue by rmoorewrs** [WindRiver-OpenSourceLabs/wr-core#11]
Running 'bitbake cube-essential' (or any bitbake target) fails with the following error. (same error shows up for all 3 architectures/targets):

******************
ERROR: Unable to parse /data/pulsar/wr-core/layers/bitbake/lib/bb/parse/parse_py/ConfHandler.py
Traceback (most recent call last):
  File "/data/pulsar/wr-core/layers/bitbake/lib/bb/parse/parse_py/ConfHandler.py", line 100, in include(parentfn='configuration INHERITs', fn='classes/package-name.bbclass', lineno=0, data=<bb.data_smart.DataSmart object at 0x7f5e6d2a6f50>, error_out='inherit'):
                 if error_out:
    >                raise ParseError("Could not %s file %s" % (error_out, fn), parentfn, lineno)
                 logger.debug(2, "CONF file '%s' not found", fn)
ParseError: ParseError in configuration INHERITs: Could not inherit file classes/package-name.bbclass
********************

Git repo was cloned and environment set up per instructions in wr-core/docs/README-intel-x86.TXT

Host is Linux Mint 17.1 Rebecca, 64-bit and have built previous versions of pulsar with no problems.

**Comment by lifupan** [comment]
Can you double check does
file /data/pulsar/wr-core/layers/meta-overc/meta-cube/classes/package-name.bbclass
existed
on your host?

Fupan


2016-07-13 1:59 GMT+08:00 rmoorewrs <notifications@github.com>:

> Running 'bitbake cube-essential' (or any target) fails with the following
> error:
> ------------------------------
>
> ERROR: Unable to parse
> /data/pulsar/wr-core/layers/bitbake/lib/bb/parse/parse_py/ConfHandler.py
> Traceback (most recent call last):
> File
> "/data/pulsar/wr-core/layers/bitbake/lib/bb/parse/parse_py/ConfHandler.py",
> line 100, in include(parentfn='configuration INHERITs',
> fn='classes/package-name.bbclass', lineno=0, data=, error_out='inherit'):
> if error_out:
> > raise ParseError("Could not %s file %s" % (error_out, fn), parentfn,
> lineno)
> logger.debug(2, "CONF file '%s' not found", fn)
> ParseError: ParseError in configuration INHERITs: Could not inherit file
> classes/package-name.bbclass
> ------------------------------
>
> Git repo was cloned and environment set up per instructions in
> wr-core/docs/README-intel-x86.TXT
>
> Host is Linux Mint 17.1 Rebecca, 64-bit and have built previous versions
> of pulsar with no problems.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/WindRiver-OpenSourceLabs/wr-core/issues/11>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AOHUoxwuxuEfo0J7nhJf7uUQ9lyQsqZ2ks5qU9XpgaJpZM4JKp95>
> .
>



-- 
不放弃，不抛弃！

        李福攀

**Comment by rmoorewrs** [comment]
Sorry, I didn't see this until after the problem was fixed... I'm guessing it wasn't there. Thanks
