### ISSUE TITLE
microzed running pulsar linux 7.0 stalls on boot up, UTMP

### ISSUE THREAD

**Issue by mnewell969** [WindRiver-OpenSourceLabs/wr-core#17]
We are running pulsar linux on our microzed processor and having very long boot up times.  The boot process stalls on 
"started Update UTMP about System Runlevel Changes"
Has anyone else run into this?  Does anyone know a solution to this?

Here is what we see on boot up:
          Starting Network Service...

```
     Starting Login Service...
```

[  OK  ] Reached target System Time Synchronized.

[  OK  ] Started Change the tty3 to be the active vt.

[  OK  ] Started Ethernet Bridge Filtering Tables.

[  OK  ] Started Permit User Sessions.

[  OK  ] Started Login Service.

[     *](2 of 2) A start job is running for Network Service (34s / 1min 53s)gre▒ GRE over IPv4 demultiplexor driver

[  OK  ] Started Open vSwitch Internal Unit.

[  OK  ] Started Network Service.

device eth0 entered promiscuous mode

IPv6: ADDRCONF(NETDEV_UP): br0: link is not ready

```
     Starting Network Name Resolution...
```

br0: port 1(eth0) entered forwarding state

br0: port 1(eth0) entered forwarding state

[  OK  ] Reached target Network.r0: link becomes ready

```
     Starting Open vSwitch...

     Starting Xinetd A Powerful Replacement For Inetd...

     Starting Setup dnsmasq...
```

[  OK  ] Started Setup dnsmasq.

```
     Starting LXC Container Initialization and Autoboot Code...

     Starting /etc/rc.local Compatibility...
```

[  OK  ] Started Network Name Resolution.

[  OK  ] Started Open vSwitch.

[  OK  ] Started Xinetd A Powerful Replacement For Inetd.

[  OK  ] Started /etc/rc.local Compatibility.

```
     Starting Getty on tty1...
```

[  OK  ] Started Getty on tty1.

[  OK  ] Reached target Login Prompts.

[  OK  ] Started LXC Container Initialization and Autoboot Code.

[  OK  ] Reached target Multi-User System.

```
     Starting Update UTMP about System Runlevel Changes...
```

[  OK  ] Started Update UTMP about System Runlevel Changes.

Pulsar Linux 7.0.0.11 cube-21-03-16-cube-server ttyPS0

**Comment by jwessel** [comment]
You might try another MicroSD card.  I have seen this occasionally and it was the result of file system operations blocking on the SD card.

**Comment by mnewell969** [comment]
Jwessel.  thanks we'll try an sandisk card instead of the kingston we've been using. I'll let you know.
Matt

**Comment by jwessel** [comment]
If the problem is not solved using another SD card device it could also be related to the timing fixes which were later provided from Avnet in the boot.bin firmware for the SD reader.  These changes are integrated into the Pulsar-8 baseline already.

**Comment by mnewell969** [comment]
Thanks Jason. I'll let you know what we find out.

________________________________

**Comment by mnewell969** [comment]
Jason,
We have our boot times down to 40s now with the new higher speed SD cards.  However, we see 20s to get to the UTMP part of the boot and then 20s to get through that step.  I'd say there is still a problem with the:
"started Update UTMP about System Runlevel Changes"

**Comment by jwessel** [comment]
The boot time on the MicroZed 7010 was around 38 seconds.

You can actually see fully what the system is up to by using the following procedure:

# Log in as root and run the following commands
cube-console dom0
cube-console essential
smart update > /dev/null
smart download systemd-analyze
mv systemd*.rpm  /var/lib/lxc/cube-server/rootfs/root
rpm -ihv /var/lib/lxc/cube-server/rootfs/root/systemd-analyze*.rpm
lxc-attach -n dom0 -- rpm -ihv /var/lib/lxc/cube-server/rootfs/root/systemd-analyze*.rpm
lxc-attach -n cube-server -- rpm -ihv /root/systemd-analyze*.rpm


systemd-analyze plot > /var/lib/lxc/cube-server/rootfs/root/1.svg
lxc-attach -n dom0 -- systemd-analyze plot > /var/lib/lxc/cube-server/rootfs/root/2.svg
lxc-attach -n cube-server -- systemd-analyze plot > /var/lib/lxc/cube-server/rootfs/root/3.svg
cat<<EOF>/var/lib/lxc/cube-server/rootfs/root/0.html
<img src=1.svg>
<br>
<img src=2.svg>
<br>
<img src=3.svg>
EOF
exit
exit


# Now copy off the data how every you choose.
scp *.html *.svg YOUR_SERVER:/YOUR_DIR

# Now that you have the files on a different machine use Chrome on the 0.html file

google-chrome 0.html

For reference, I provided the files I generated here:

http://htmlpreview.github.io/?https://github.com/jwessel/scratch/blob/master/MZ/pulsar-7-7010-boot/0.html

**Comment by masselstine** [comment]
Pulsar7 is effectively no longer being developed and most people should have moved to Pulsar8 by this point in time. Please open a new issue in against Pulsar8 if this remains an issue there.
