### ISSUE TITLE
Is there an error in wr-core/docs/README-intel-x86.TXT?

### ISSUE THREAD

**Issue by rmoorewrs** [WindRiver-OpenSourceLabs/wr-core#28]
Two examples in README-intel-x86.TXT are confusing and it looks like one is wrong, but I can't tell which is wrong or right.

Here's the instruction for building a self-bootable image for IntelCubeDesktop. The 'target-config' parameter seems to be missing a path? Or is this correct?
```
# Build a self-bootable image for IntelCubeDesktop board
sudo ../overc-installer/sbin/cubeit \ 
--force \ 
--config `pwd`/../install_templates/IntelCubeDesktop/IntelCubeDesktop-live.sh \ 
--target-config IntelCubeDesktop-live.sh \ 
--artifacts `pwd`/tmp/deploy/images/intel-corei7-64 \ 
pulsar8-intelcubedesktop.img
```

Here's the instruction for building an installer image that writes directly to a USB drive. Where is the part that specifies that it's an installer? Other than the --target-config having a full path and writing to $DEV, it looks identical to the other example.
```
# Or build an installer image or USB stick
#DEV=/dev/NBD_DEVICE  or a USB storage device
sudo ../overc-installer/sbin/cubeit \ 
--force \ 
--config `pwd`/../install_templates/IntelCubeDesktop/IntelCubeDesktop-live.sh \ 
--target-config `pwd`/../install_templates/IntelCubeDesktop/IntelCubeDesktop-live.sh \ 
--artifacts `pwd`/tmp/deploy/images/intel-corei7-64 \ 
$DEV
```

Please correct and/or clarify this...

BTW, This also appears in the apollo-lake README and probably others.

**Comment by rmoorewrs** [comment]
OK, reading the usage on cubeit, I see that the --target-config is only for the installer... It would be nice if we had a little better documentation on utilities like cubeit...

**Comment by masselstine** [comment]
Whether you get an installer image vs. a bootable image is determined by the <target>/last parameter to cubeit. This is documented in the cubeit usage text https://github.com/OverC/overc-installer/blob/master/sbin/cubeit#L35. --target-config is actually used in both situations.

**Comment by rmoorewrs** [comment]
OK, Thanks Mark for the explanation. Since there are valid use cases for
installer images and live-desktop bootable USBs (in addition to the other
two already supported), wouldn't it make sense to specify
(installer|live-desktop) explicitly and then allow (image file| direct
write to $DEV) as an independent choice?

Thanks,

Rich
