### ISSUE TITLE
Creating kvm VM with libvirt fails, /var/run/libvirt/virtlogd-sock not found

### ISSUE THREAD

**Issue by rmoorewrs** [WindRiver-OpenSourceLabs/wr-core#30]
Problem
-----------
Creating a new kvm virtual machine with libvirt fails with this error:

```
# virsh create my_vm.xml 
error: Failed to create domain from my_vm.xml
error: Failed to connect socket to '/var/run/libvirt/virtlogd-sock': No such file or directory
```

The error is the same whether creating locally with virsh or remotely with virt-manager.

Pulsar image version: [Intel Computestick official binary image from 2016-11-07 22:34](https://distro.windriver.com/public_feeds/WindRiver-Pulsar-Linux-Intel-Compute-Stick-image/Releases/Latest/pulsar8-intel-computestick.img.zip)

Steps to reproduce:
--------------------------
1) boot official compute stick image
2) install the required libvirt/kvm files
3) scp a working kvm image to /var/lib/libvirt/images on pulsar machine
4) Dump xml config file for the same image on host and scp to pulsar machine:
```
virsh dumpxml my_vm > my_vm.xml
```
5) Create VM on pulsar machine
```
# virsh create my_vm.xml
```
- may have to edit the xml file for compatible machine name, image path, virtual net,  etc

or connect to pulsar machine with virt-manager and create a new VM using the image scp'ed above... result is the same.

**Comment by rmoorewrs** [comment]
OK, I figured out the problem was that virtlogd wasn't running, so it has to be started/permanently enabled with systemctl:

```
# systemctl enable virtlogd.socket
```

**Comment by masselstine** [comment]
Thanks for the follow up. I was just getting to this now but see you have met with success. On to other things...
