### ISSUE TITLE
systemd-modules-load show failed in dmesg

### ISSUE THREAD

**Issue by yunguowei** [WindRiver-OpenSourceLabs/wr-core#32]
[    3.720296] systemd[1]: systemd-modules-load.service: Main process exited, code=exited, status=1/FAILURE
[    3.726856] Switched to clocksource tsc
[    3.728488] systemd[1]: Failed to start Load Kernel Modules.
[    3.740585] systemd[1]: systemd-modules-load.service: Unit entered failed state.
[    3.743889] systemd[1]: systemd-modules-load.service: Failed with result 'exit-code'.

**Comment by masselstine** [comment]
This was broken by a commit in oe-core (0ccb2efe9837e2915c093341a662dffc1df00866 - kernel: Modify kernel modules installation path.). It is in the process of being reverted.

**Comment by masselstine** [comment]
The revert for relocating the kernel modules has been merged to oe-core for a while now and this issue is no longer being seen so closing this.
----
commit 85cec1e3df68e932c7b210956ef5f17b85f3616f
Author: Jason Wessel <jason.wessel@windriver.com>
Date:   Thu Jan 19 13:14:41 2017 -0800

    Revert "kernel: Modify kernel modules installation path."
