### ISSUE TITLE
kernel menuconfig failed on pulsar linux

### ISSUE THREAD

**Issue by aaronadlink** [WindRiver-OpenSourceLabs/wr-core#36]
Hi, all

I try to build pulsar image for apollo lake is success.
I want to modify kernel configuration so i execute "bitbake linux-yocto -c menuconfig"
but i got this error message on another terminal:
---------------------------------------------------------------------
make: *** No rule to make target `menuconfig'.  Stop.
Command failed.
Press any key to continue... 
---------------------------------------------------------------------

how could i dynamic change kernel configure on pulsar linux ?
Thanks.

**Comment by rmoorewrs** [comment]
I think you're using the wrong linux name. Look at local.conf in build-intel-apollolake/conf/local.conf and find  the line with "PREFERRED_PROVIDER_virtual/kernel_intel-corei7-64=" and use the name to the right of the =.

For the Intel compute stick, it's "linux-yocto-rt". Substitute whatever it is for 'linux-yocto' in your line above, e.g.

bitbake linux-yocto-rt -c menuconfig

That worked for me.

**Comment by aaronadlink** [comment]
my local.conf show
PREFERRED_PROVIDER_virtual/kernel_intel-corei7-64 = "linux-yocto"
so execute " bitbake linux-yocto -c menuconfig" is right , But it still fails .  Why ?

**Comment by rmoorewrs** [comment]
IDK... it works for me on build-intel-x86. but I'll do an apollo lake build and try it on my system and let you know.

In the meantime, you could try an intel-x86 build and see if it works for you there. That would help rule out a build host issue.

**Comment by rmoorewrs** [comment]
just got the chance to try this on an apollo_lake build and it did work fine for me. Linux Mint 17.3 (ubuntu 14.04) system, btw.

**Comment by masselstine** [comment]
@aaronadlink what about running other commands like 'bitbake linux-yocto -c listtasks'? Can you try this and post the output?

**Comment by aaronadlink** [comment]
NOTE: Preparing RunQueue
NOTE: Executing RunQueue Tasks
do_build                       Default task for a recipe - depends on all other normal tasks required to 'build' a recipe
do_bundle_initramfs            Combines an initial ramdisk image and kernel together to form a single image
do_check_user_keys             
do_checkuri                    Validates the SRC_URI value
do_checkuriall                 Validates the SRC_URI value for all recipes required to build a target
do_clean                       Removes all output files for a target
do_cleanall                    Removes all output files, shared state cache, and downloaded source files for a target
do_cleansstate                 Removes all output files and shared state cache for a target
do_compile                     Compiles the source in the compilation directory
do_compile_kernelmodules       Compiles loadable modules for the Linux kernel
do_configure                   Configures the source by enabling and disabling any build-time and configuration options for the software being built
do_deploy                      Writes deployable output files to the deploy directory
do_deploy_setscene             Writes deployable output files to the deploy directory (setscene version)
do_devpyshell                  Starts an interactive Python shell for development/debugging
do_devshell                    Starts a shell with the environment set up for development/debugging
do_diffconfig                  Compares the old and new config files after running do_menuconfig for the kernel
do_fetch                       Fetches the source code
do_fetchall                    Fetches all remote sources required to build a target
do_install                     Copies files from the compilation directory to a holding area
do_kernel_checkout             Checks out source/meta branches for a linux-yocto style kernel
do_kernel_configcheck          Validates the kernel configuration for a linux-yocto style kernel
do_kernel_configme             Assembles the kernel configuration for a linux-yocto style kernel
do_kernel_link_vmlinux         Creates a symbolic link in arch/$arch/boot for vmlinux kernel images
do_kernel_metadata             
do_listtasks                   Lists all defined tasks for a target
do_menuconfig                  Runs 'make menuconfig' for the kernel
do_package                     Analyzes the content of the holding area and splits it into subsets based on available packages and files
do_package_qa                  Runs QA checks on packaged files
do_package_qa_setscene         Runs QA checks on packaged files (setscene version)
do_package_setscene            Analyzes the content of the holding area and splits it into subsets based on available packages and files (setscene version)
do_package_write_rpm           Creates the actual RPM packages and places them in the Package Feed area
do_package_write_rpm_setscene  Creates the actual RPM packages and places them in the Package Feed area (setscene version)
do_packagedata                 Creates package metadata used by the build system to generate the final packages
do_packagedata_setscene        Creates package metadata used by the build system to generate the final packages (setscene version)
do_patch                       Locates patch files and applies them to the source code
do_populate_lic                Writes license information for the recipe that is collected later when the image is constructed
do_populate_lic_setscene       Writes license information for the recipe that is collected later when the image is constructed (setscene version)
do_populate_sysroot            Copies a subset of files installed by do_install into the sysroot in order to make them available to other recipes
do_populate_sysroot_setscene   Copies a subset of files installed by do_install into the sysroot in order to make them available to other recipes (setscene version)
do_savedefconfig               Creates a minimal Linux kernel configuration file
do_shared_workdir              
do_shared_workdir_setscene      (setscene version)
do_sign                        
do_sign_kernel_initramfs       
do_sizecheck                   Checks the size of the kernel image against KERNEL_IMAGE_MAXSIZE (if set)
do_strip                       Strips unneeded sections out of the Linux kernel image
do_uboot_mkimage               Creates a uImage file from the kernel for the U-Boot bootloader
do_unpack                      Unpacks the source code into a working directory
do_validate_branches           Ensures that the source/meta branches are on the locations specified by their SRCREV values for a linux-yocto style kernel
NOTE: Tasks Summary: Attempted 1 tasks of which 0 didn't need to be rerun and all succeeded.

Summary: There was 1 WARNING message shown.

**Comment by masselstine** [comment]
Can you please run

bitbake linux-yocto -c compile -f
bitback linux-yocto -c menuconfig

It almost feels as though the kernel build area is not yet populated (possibly because things are being pulled out of sstate?). The dependencies should prevent this but I want to rule this out.

**Comment by aaronadlink** [comment]
aaron@ubuntu:~/slicedpie/wr-core/build-intel-apollolake$ bitbake linux-yocto -c compile -f
Loading cache: 100% |##########################################################################################################| ETA:  00:00:00
Loaded 5729 entries from dependency cache.
Parsing recipes: 100% |########################################################################################################| Time: 00:00:01
Parsing of 2559 .bb files complete (2555 cached, 4 parsed). 5735 targets, 511 skipped, 9 masked, 0 errors.
WARNING: No recipes available for:
  /home/aaron/slicedpie/wr-core/layers/meta-virtualization/recipes-kernel/linux/linux-yocto_4.8.bbappend
  /home/aaron/slicedpie/wr-core/layers/meta-gateway/recipes-core-luci/busybox/busybox_1.22.1.bbappend
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION        = "1.28.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "Ubuntu-14.04"
DISTRO            = "wrlinux-small"
DISTRO_VERSION    = "8.0.0.6"
MACHINE           = "intel-corei7-64"
DEFAULTTUNE       = "core2-64"
TARGET_SYS        = "x86_64-wrs-linux"
TUNE_FEATURES     = "m64 core2"
TARGET_FPU        = ""
lib32:  DEFAULTTUNE       = "x86"
lib32:  TARGET_SYS        = "i686-wrsmllib32-linux"
lib32:  TUNE_FEATURES     = "m32"
wrlinux           = "HEAD:a2479440b210e88013388050dca4e6d2e468fe54"
meta              = "HEAD:ae2ea29104a3f49d3b6e8014f2dc38c3a758c19b"
oe-meta-go        = "HEAD:b29b384eae4a40933d07cc64c51e890c289d9621"
meta-dpdk         = "HEAD:48b110531ddcb7d7595aba13226b8ad687d269fc"
meta-virtualization = "HEAD:2e15a6fea032fd1cb4de044ea1441b92d84caa48"
external-binaries = "HEAD:bfa287c257e260fc874661f32f28aaa21a69fe1b"
meta-xfce         
meta-webserver    
meta-perl         
meta-python       
meta-oe           
meta-gnome        
meta-multimedia   
meta-networking   
meta-filesystems  
meta-initramfs    = "HEAD:ceafa24a6c4bd6ec7f0f0340209b539600c09e96"
meta-security     = "HEAD:0ba8cd8b2095b501baa86e8bf95dbf525d095b29"
meta-browser      = "HEAD:77736988073a5d90fcff9d0005c8477332ede387"
meta-cloud-services = "HEAD:887f2154c5aaeaff6de2efb65cc1118cfb5eb904"
meta-cube         = "HEAD:601f5270ef8b049033838d99965fb22a18936e5d"
wr-hac-agent      = "HEAD:be8de65d157d33dbac3fd882f1bd7c7b06e0c353"
wr-tools-debug    = "HEAD:e982f9b02294010844ba9510909dbf5361bbd21d"
wr-fixes          = "HEAD:60c9971b9c64c52e2baf8d99c494fa64385b5e97"
wr-base           = "HEAD:a8b8d7e8c942d2f72cc6e6c012a287582316172a"
meta-gateway      = "HEAD:f0430303be2c56fe6a9c038f0d564ebff954a0eb"
intel-apollolake  = "HEAD:2b6c67e7ae7593f3b7d5fa288cc5dae6e859d04a"
meta-intel        = "HEAD:3957e4d5044d16170ef52cc7ec6ea513c968137b"
wr-kernel         = "HEAD:4745a82207751290e76986b52e21f0cf1ba70205"
meta-measured     = "HEAD:109af9cf95bf9ee48e0c41f53337e533dfb90be5"
meta-secure-env   = "HEAD:68d5edf70046ef4e72b6d653dfd226e97152bf50"
wrlabs-integration = "HEAD:ed0d970d8e50a12ca718d2c6c2b0fbccf3d7e8c9"

NOTE: Preparing RunQueue
NOTE: Tainting hash to force rebuild of task /home/aaron/slicedpie/wr-core/layers/oe-core/meta/recipes-kernel/linux/linux-yocto_4.1.bb, do_compile
WARNING: /home/aaron/slicedpie/wr-core/layers/oe-core/meta/recipes-kernel/linux/linux-yocto_4.1.bb.do_compile is tainted from a forced run
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
NOTE: Tasks Summary: Attempted 341 tasks of which 340 didn't need to be rerun and all succeeded.

Summary: There were 2 WARNING messages shown.
aaron@ubuntu:~/slicedpie/wr-core/build-intel-apollolake$ bitbake linux-yocto -c menuconfig
Loading cache: 100% |##########################################################################################################| ETA:  00:00:00
Loaded 5731 entries from dependency cache.
Parsing recipes: 100% |########################################################################################################| Time: 00:00:01
Parsing of 2559 .bb files complete (2556 cached, 3 parsed). 5735 targets, 511 skipped, 9 masked, 0 errors.
WARNING: No recipes available for:
  /home/aaron/slicedpie/wr-core/layers/meta-virtualization/recipes-kernel/linux/linux-yocto_4.8.bbappend
  /home/aaron/slicedpie/wr-core/layers/meta-gateway/recipes-core-luci/busybox/busybox_1.22.1.bbappend
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION        = "1.28.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "Ubuntu-14.04"
DISTRO            = "wrlinux-small"
DISTRO_VERSION    = "8.0.0.6"
MACHINE           = "intel-corei7-64"
DEFAULTTUNE       = "core2-64"
TARGET_SYS        = "x86_64-wrs-linux"
TUNE_FEATURES     = "m64 core2"
TARGET_FPU        = ""
lib32:  DEFAULTTUNE       = "x86"
lib32:  TARGET_SYS        = "i686-wrsmllib32-linux"
lib32:  TUNE_FEATURES     = "m32"
wrlinux           = "HEAD:a2479440b210e88013388050dca4e6d2e468fe54"
meta              = "HEAD:ae2ea29104a3f49d3b6e8014f2dc38c3a758c19b"
oe-meta-go        = "HEAD:b29b384eae4a40933d07cc64c51e890c289d9621"
meta-dpdk         = "HEAD:48b110531ddcb7d7595aba13226b8ad687d269fc"
meta-virtualization = "HEAD:2e15a6fea032fd1cb4de044ea1441b92d84caa48"
external-binaries = "HEAD:bfa287c257e260fc874661f32f28aaa21a69fe1b"
meta-xfce         
meta-webserver    
meta-perl         
meta-python       
meta-oe           
meta-gnome        
meta-multimedia   
meta-networking   
meta-filesystems  
meta-initramfs    = "HEAD:ceafa24a6c4bd6ec7f0f0340209b539600c09e96"
meta-security     = "HEAD:0ba8cd8b2095b501baa86e8bf95dbf525d095b29"
meta-browser      = "HEAD:77736988073a5d90fcff9d0005c8477332ede387"
meta-cloud-services = "HEAD:887f2154c5aaeaff6de2efb65cc1118cfb5eb904"
meta-cube         = "HEAD:601f5270ef8b049033838d99965fb22a18936e5d"
wr-hac-agent      = "HEAD:be8de65d157d33dbac3fd882f1bd7c7b06e0c353"
wr-tools-debug    = "HEAD:e982f9b02294010844ba9510909dbf5361bbd21d"
wr-fixes          = "HEAD:60c9971b9c64c52e2baf8d99c494fa64385b5e97"
wr-base           = "HEAD:a8b8d7e8c942d2f72cc6e6c012a287582316172a"
meta-gateway      = "HEAD:f0430303be2c56fe6a9c038f0d564ebff954a0eb"
intel-apollolake  = "HEAD:2b6c67e7ae7593f3b7d5fa288cc5dae6e859d04a"
meta-intel        = "HEAD:3957e4d5044d16170ef52cc7ec6ea513c968137b"
wr-kernel         = "HEAD:4745a82207751290e76986b52e21f0cf1ba70205"
meta-measured     = "HEAD:109af9cf95bf9ee48e0c41f53337e533dfb90be5"
meta-secure-env   = "HEAD:68d5edf70046ef4e72b6d653dfd226e97152bf50"
wrlabs-integration = "HEAD:ed0d970d8e50a12ca718d2c6c2b0fbccf3d7e8c9"

NOTE: Preparing RunQueue
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
Currently 1 running tasks (340 of 340):
0: linux-yocto-4.1.27+gitAUTOINC+b28f454e26_6e06dacda2-r0 do_menuconfig (pid 25641)

== Other terminal
make: *** No rule to make target `menuconfig'.  Stop.
Command failed.
Press any key to continue...

**Comment by masselstine** [comment]
Can you please run

bitbake linux-yocto -e | grep "^KBUILD_OUTPUT"

Then post the content of the Makefile found in the directory output by the above command.

Basically what appears to be happening is that "make" is not actually finding the above Makefile or the one which it references via '-C'. The error msg is slightly different for each case so it leads me to think that it is the first case.

Do you have any bbappend files for the kernel?

**Comment by aaronadlink** [comment]
aaron@ubuntu:~/slicedpie/wr-core/build-intel-apollolake$ bitbake linux-yocto -e | grep "^KBUILD_OUTPUT"

KBUILD_OUTPUT="/home/aaron/slicedpie/wr-core/build-intel-apollolake/tmp/work/core2-64-intel-common-wrs-linux/linux-yocto/4.1.27+gitAUTOINC+b28f454e26_6e06dacda2-r0/linux-core2-64-intel-common-standard-build"

===============================================================
# Automatically generated by /home/aaron/slicedpie/wr-core/build-intel-apollolake/tmp/work-shared/intel-corei7-64/kernel-source/scripts/mkmakefile: don't edit

VERSION = 4
PATCHLEVEL = 1

lastword = $(word $(words $(1)),$(1))
makedir := $(dir $(call lastword,$(MAKEFILE_LIST)))

ifeq ("$(origin V)", "command line")
VERBOSE := $(V)
endif
ifneq ($(VERBOSE),1)
Q := @
endif

MAKEARGS := -C /home/aaron/slicedpie/wr-core/build-intel-apollolake/tmp/work-shared/intel-corei7-64/kernel-source
MAKEARGS += O=$(if $(patsubst /%,,$(makedir)),$(CURDIR)/)$(patsubst %/,%,$(makedir))

MAKEFLAGS += --no-print-directory

.PHONY: __sub-make $(MAKECMDGOALS)

__sub-make:
        $(Q)$(MAKE) $(MAKEARGS) $(MAKECMDGOALS)

$(filter-out __sub-make, $(MAKECMDGOALS)): __sub-make
        @:

====================================================
Do you have any bbappend files for the kernel?
 Ans:  No. i don't have change it.

**Comment by aaronadlink** [comment]
i reinstall ubuntu and try again
this issue is gone
i don't known why my old ubuntu env what happened.  =.=

**Comment by masselstine** [comment]
Everything looks fine with the Makefile. I can only assume there was an issue with ;make' itself which was causing this, maybe it not respecting the '-C' arg? I can't be certain. At any rate I will mark this issue as closed, cause and fix unknown. Thanks for pushing through this.

**Comment by jcdr** [comment]
I was able to accidentally reproduce this bug after installing tmux package on openSUSE Leap 15.0 while using Poky thud. This was solved by simply removing the tmux package. It look like Yocto try to use tmux if present but with a obviously broken code.

**Comment by masselstine** [comment]
Interesting. I usually have tmux present on systems I make use of as I use byobu. And although there were menuconfig issues years back I haven't seen any in recent memory. I suppose it could be related to the openSUSE tmux configuration or version.
