### ISSUE TITLE
pulsar8 cube-dom0 fails for intel-x86, dies building cups

### ISSUE THREAD

**Issue by rmoorewrs** [WindRiver-OpenSourceLabs/wr-core#38]
Pulsar 8 dies while building cube-dom0 on build-intel-x86 ... problem seems to be while building cups. log file attached.
 
This is a fresh git pull, fully updated, following git clone and process in reaadme.txt

[log.do_compile.16220.zip](https://github.com/WindRiver-OpenSourceLabs/wr-core/files/812659/log.do_compile.16220.zip)

**Comment by rmoorewrs** [comment]
Looks like this is a problem in the cups recipe. I had to disable avahi and then it compiled. I realize this is probably an oe_core issue, but it breaks the build -- please fix this! If you have a better answer, please let me know.

No idea what problems might arise from turning off avahi in cups, but I don't need cups anyway and would just as soon exclude it from my build (but that's more complicated than just configuring avahi out).

For others who might run into this problem:

- edit this file:
`<proj_dir>/wr-core/layers/oe-core/meta/recipes-extended/cups/cups.inc`

- find the line starting with `EXTRA_OECONF`

- add `--disable-avahi` to the list, e.g.

```
EXTRA_OECONF = " \
               --enable-gnutls \
               --enable-dbus \
               --enable-browsing \
               --disable-gssapi \
               --enable-debug \
               --disable-relro \
               --enable-libusb \
               --without-php \
               --without-perl \
               --without-python \
               --without-java \
               --disable-avahi \
               DSOFLAGS='${LDFLAGS}' \
               "
```

**Comment by masselstine** [comment]
I am actually really surprised your workaround actually worked. My build has a PACKAGECONFIG which already disables avahi. The cups code however pretty much requires that we either have DNSSD or avahi, yet doesn't complain until you build if you don't have one or the other. Look at findipp.c though

typedef struct ippfind_srv_s            /* Service information */
{
#ifdef HAVE_DNSSD
  DNSServiceRef ref;                    /* Service reference for query */
#elif defined(HAVE_AVAHI)
  AvahiServiceResolver *ref;            /* Resolver */
#endif /* HAVE_DNSSD */
  char          *name,                  /* Service name */
                *domain,                /* Domain name */
                *regtype,               /* Registration type */
                *fullName,              /* Full name */
                *host,                  /* Hostname */
                *resource,              /* Resource path */
                *uri;                   /* URI */
  int           num_txt;                /* Number of TXT record keys */
  cups_option_t *txt;                   /* TXT record keys */
  int           port,                   /* Port number */
                is_local,               /* Is a local service? */
                is_processed,           /* Did we process the service? */
                is_resolved;            /* Got the resolve data? */
} ippfind_srv_t;

Note that the 'ref' element is only defined if DNS_SD or Avahi is "enabled" but then later on in that file they have code like the following:

          if (service->ref)
          {
#ifdef HAVE_DNSSD
            DNSServiceRefDeallocate(service->ref);
#else
            avahi_service_resolver_free(service->ref);
#endif /* HAVE_DNSSD */

            service->ref = NULL;
          }

NOTE that ->ref is accessed when it shouldn't exist. I am trying to track down what changed to cause this but unfortunately this is anything but straight forward.

**Comment by masselstine** [comment]
Please work around this for now by adding the following to your local.conf

PACKAGE_CONFIG_cups_append += "avahi"

A fix is in the works and will hopefully be available soon.

**Comment by rmoorewrs** [comment]
Yeah, must've tried playing with something else to get cups to compile, which was likely the the cause of the libdrm issue.

I did try adding `PACKAGE_CONFIG_cups_append += "avahi"` to local.conf and restoring the original cups.inc, but I still get the same compile error.

**Comment by masselstine** [comment]
If you are fixing an existing build you will most likely have to do

bitbake cups -C configure

**Comment by rmoorewrs** [comment]
That didn't work either but I started with a fresh build, added avahi to local.conf and that finally build a system. Thanks for your help.

**Comment by masselstine** [comment]
Sounds good. I will go with the story that some of your other attempts at addressing the issue were causing the issue. Glad you are building successfully now. I will close this case once I know the proper fix is complete and merged.

**Comment by aminenajahi** [comment]
I had the same issue sporadically happening on clean builds. 

The dependency chain is : cube-dom0 -> packagegroup-dom0 -> packagegroup-dom0-fs->samba->cups

I was able to to temporary fix the issue by removing samba from the build, until it get fixed upstream.
RDEPENDS_packagegroup-dom0-fs_remove_pn-packagegroup-dom0 = "samba"

If you still need it, this should work too:

**Comment by jwessel** [comment]
I believe this was fixed quite a while back. If it is still a problem, please re-open. 

Fixed by this commit: https://github.com/WindRiver-OpenSourceLabs/wrlabs-integration/commit/70dbe4e400a1766ab73ac6bfe5186f3b41ca2c8d
