### ISSUE TITLE
PCIe not functional

### ISSUE THREAD

**Issue by h-qdi** [WindRiver-OpenSourceLabs/wr-core#4]
Hello,

We are using Windriver Pulsar (image from Github) with Zynq Avnet M-ITX. There are no PCI entries /proc/bus when accessed from different containers.

How do we resolve the issue? Is PCIe functionality enabled at all?

Thank you!

**Comment by lifupan** [comment]
The PCIe feature wasn't enabled on it, and we can enable it  in the
following RCPL updates.

Fupan

2016-03-04 7:17 GMT+08:00 h-qdi <notifications@github.com>:

> Hello,
>
> We are using Windriver Pulsar (image from Github) with Zynq Avnet M-ITX.
> There are no PCI entries /proc/bus when accessed from different containers.
>
> How do we resolve the issue? Is PCIe functionality enabled at all?
>
> Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WindRiver-OpenSourceLabs/wr-core/issues/4>.
>



-- 
不放弃，不抛弃！

        李福攀

**Comment by h-qdi** [comment]
Hello Fupan,

We were able to get our hands on a uImage with PCIe enabled. 

Currently, when we use a VGA device such as GPU in the slot, PCIe BARs are not being assigned to the device and remains disabled after boot-up. Can we get some help in solving this issue?

Thank you!

**Comment by lifupan** [comment]
You should make sure the following three kernel options
have been enabled:

CONFIG_PCI=y
CONFIG_PCI_MSI=y
CONFIG_PCIE_XILINX=y


Fupan


2016-03-11 6:58 GMT+08:00 h-qdi <notifications@github.com>:

> Hello Fupan,
>
> We were able to get our hands on a uImage with PCIe enabled.
>
> Currently, when we use a VGA device such as GPU in the slot, PCIe BARs are
> not being assigned to the device and remains disabled after boot-up. Can we
> get some help in solving this issue?
>
> Thank you!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WindRiver-OpenSourceLabs/wr-core/issues/4#issuecomment-195088918>
> .
>



-- 
不放弃，不抛弃！

        李福攀

**Comment by masselstine** [comment]
@h-qdi has this issue been resolved?

**Comment by jwessel** [comment]
Closing issue since PCIe support was shown working on the ATX version of the board.
