### ISSUE TITLE
Default login to image is not root/root??

### ISSUE THREAD

**Issue by jakob-engblom-i** [WindRiver-OpenSourceLabs/wr-core#45]
I have built the default Intel NUC image for Pulsar from this github repo, and booted it on top of a Simics target machine.  Works fine to boot, but it seems it does not like me logging in as root/root.  The default login prompt does not accept that.  Has this changed, and is there some way to configure this in the build?

**Comment by jiazhang0** [comment]
The default password is incendia. See http//github.com/WindRiver-OpenSourceLabs/wrlabs-integration/tree/pulsar-8/templates/default/template.conf for how to configure it.

**Comment by jakob-engblom-i** [comment]
Excellent!

I think https://github.com/WindRiver-OpenSourceLabs/wr-core/blob/pulsar-8/docs/README-intel-x86.TXT has to be updated to not list "root/root" as the login.

**Comment by jiazhang0** [comment]
Thanks for reporting this doc issue. I have submitted a PR to correct all invalid passwords recorded in docs. https://github.com/WindRiver-OpenSourceLabs/wr-core/pull/46
