### ISSUE TITLE
Some README description is incorrect

### ISSUE THREAD

**Issue by aaronadlink** [WindRiver-OpenSourceLabs/wr-core#47]
README-intel-apollolake.TXT  :  password is not "root"   !     default password is incendia
README-intel-apollolake-secure-full-feature.TXT :    env is not "init-intel-apollolake-env"  !     it is init-intel-apollolake-secure-full-feature-env , right ?

**Comment by jiazhang0** [comment]
Thanks for reporting these issues. A new PR already addresses these issues. See https://github.com/WindRiver-OpenSourceLabs/wr-core/pull/46
