### ISSUE TITLE
Scroll-back is disabled in Putty (intel-apollolake)

### ISSUE THREAD

**Issue by aaronadlink** [WindRiver-OpenSourceLabs/wr-core#48]
The Wind River Pulsar Linux (intel-apollolake) we can only see the current lines. The scroll-bar on the right hand side is greyed out.
The Wind River Pulsar is using this “alternate screen” mode as the default, not only in text editors. Is this a configuration? Can it be changed ?
Or , There are special reasons for use the alternate screen on default configure !

Thanks.

**Comment by jwessel** [comment]
There was no particular reason driving the use of the alternate screen.  

We can use the following in the /etc/default/screen-gettyrc to solve the problem.

termcapinfo xterm ti@:te@

https://github.com/WindRiver-OpenSourceLabs/wr-core/commit/0d437ebb80c5400fbaf10229c4114acf76461fad
