### ISSUE TITLE
Build error in qemu_native

### ISSUE THREAD

**Issue by robinristow** [WindRiver-OpenSourceLabs/wr-core#5]
I'm seeing a build issue (below) when following the instructions in README-Intel-x86.txt.  (libsdl[1.2,2]-dev are installed on host.)

Build Configuration:
BB_VERSION        = "1.24.0"
BUILD_SYS         = "x86_64-linux"
NATIVELSBSTRING   = "Ubuntu-15.10"
DISTRO            = "wrlinux-small"
DISTRO_VERSION    = "7.0.0.11"
MACHINE           = "intel-corei7-64"
DEFAULTTUNE       = "core2-64"
TARGET_SYS        = "x86_64-wrs-linux"
TUNE_FEATURES     = "m64 core2"
TARGET_FPU        = ""

Error message:
ERROR: Function failed: do_configure (log file is located at /home/rristow/Pulsar/wr-core/build-intel-x86/tmp/work/x86_64-linux/qemu-native/2.1.2-r0/temp/log.do_configure.14781)
ERROR: Logfile of failure stored in: /home/rristow/Pulsar/wr-core/build-intel-x86/tmp/work/x86_64-linux/qemu-native/2.1.2-r0/temp/log.do_configure.14781
Log data follows:
| DEBUG: Executing python function sysroot_cleansstate
| DEBUG: Python function sysroot_cleansstate finished
| DEBUG: Executing shell function autotools_preconfigure
| DEBUG: Shell function autotools_preconfigure finished
| DEBUG: Executing python function autotools_copy_aclocals
| DEBUG: Python function autotools_copy_aclocals finished
| DEBUG: Executing shell function do_configure
| 
| ERROR: User requested feature sdl
|        configure was not able to find it.
|        Install SDL devel
| 
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_configure (log file is located at /home/rristow/Pulsar/wr-core/build-intel-x86/tmp/work/x86_64-linux/qemu-native/2.1.2-r0/temp/log.do_configure.14781)
ERROR: Task 188 (virtual:native:/home/rristow/Pulsar/wr-core/layers/oe-core/meta/recipes-devtools/qemu/qemu_2.1.2.bb, do_configure) failed with exit code '1'
NOTE: Tasks Summary: Attempted 931 tasks of which 0 didn't need to be rerun and 1 failed.

**Comment by lifupan** [comment]
What's the issue linux of your built host, have you run
scripts/host_package_install.sh on your host to
install the built required tools?

Fupan

2016-03-26 1:15 GMT+08:00 robinristow <notifications@github.com>:

> I'm seeing a build issue (below) when following the instructions in
> README-Intel-x86.txt. (libsdl[1.2,2]-dev are installed on host.)
>
> Build Configuration:
> BB_VERSION = "1.24.0"
> BUILD_SYS = "x86_64-linux"
> NATIVELSBSTRING = "Ubuntu-15.10"
> DISTRO = "wrlinux-small"
> DISTRO_VERSION = "7.0.0.11"
> MACHINE = "intel-corei7-64"
> DEFAULTTUNE = "core2-64"
> TARGET_SYS = "x86_64-wrs-linux"
> TUNE_FEATURES = "m64 core2"
> TARGET_FPU = ""
>
> Error message:
> ERROR: Function failed: do_configure (log file is located at
> /home/rristow/Pulsar/wr-core/build-intel-x86/tmp/work/x86_64-linux/qemu-native/2.1.2-r0/temp/log.do_configure.14781)
> ERROR: Logfile of failure stored in:
> /home/rristow/Pulsar/wr-core/build-intel-x86/tmp/work/x86_64-linux/qemu-native/2.1.2-r0/temp/log.do_configure.14781
> Log data follows:
> | DEBUG: Executing python function sysroot_cleansstate
> | DEBUG: Python function sysroot_cleansstate finished
> | DEBUG: Executing shell function autotools_preconfigure
> | DEBUG: Shell function autotools_preconfigure finished
> | DEBUG: Executing python function autotools_copy_aclocals
> | DEBUG: Python function autotools_copy_aclocals finished
> | DEBUG: Executing shell function do_configure
> |
> | ERROR: User requested feature sdl
> | configure was not able to find it.
> | Install SDL devel
> |
> | WARNING: exit code 1 from a shell command.
> | ERROR: Function failed: do_configure (log file is located at
> /home/rristow/Pulsar/wr-core/build-intel-x86/tmp/work/x86_64-linux/qemu-native/2.1.2-r0/temp/log.do_configure.14781)
> ERROR: Task 188
> (virtual:native:/home/rristow/Pulsar/wr-core/layers/oe-core/meta/recipes-devtools/qemu/
> qemu_2.1.2.bb, do_configure) failed with exit code '1'
> NOTE: Tasks Summary: Attempted 931 tasks of which 0 didn't need to be
> rerun and 1 failed.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/WindRiver-OpenSourceLabs/wr-core/issues/5>
>



-- 
不放弃，不抛弃！

        李福攀

**Comment by edhaynes** [comment]
I'm seeing the same thing.  This is with fresh Ubuntu 16.04 install and I then ran the host_package_install.sh scripts.

**Comment by tuyenth** [comment]
Hi Guys,
I have a workaround for this issue.
1. Comment line #ASSUME_PROVIDED += "libsdl-native" in meta/conf/local.conf.sample file
2. Comment line #PACKAGECONFIG[sdl] = "--enable-sdl,--disable-sdl,libsdl ${NATIVEDEPS}," in qemu/qemu.inc file.
3. Resource environment again.
4. re-run build.

Good luck!!!

**Comment by AlexanderStohr** [comment]
i have no idea why an automated embedded cross build would need the SDL feature of qemu in the first row. it should be save to disable those feature by default as it has prooven to be a typical point of failure for todays standard build hosts (e.g. Ubuntu 16.0.4 LTS). you might want to send this proposal upstream so that all other projects based on the same source can benefit from it, e.g. Yocto.

**Comment by masselstine** [comment]
Fixed by https://github.com/WindRiver-OpenSourceLabs/wr-core/commit/11c1be7e5bd98a5b0d0d781278cc2bd5fe1e1f9f
