### ISSUE TITLE
4G modules mac address all zero [apollo lake]

### ISSUE THREAD

**Issue by aaronadlink** [WindRiver-OpenSourceLabs/wr-core#50]
I try use sierra mc7430 on intel apollo lake pulsar linux . 
Default support sierra mc7450 on apollo lake pulsar linux .
The sierra mc7430 have same pid & vid with mc7450 and both are only support raw-ip mode .
It would work fine on test result. It could got ip address and connect to internet.
But the Mac address display is zero on luci when it switches to raw-ip mode.
HWaddr all zero is normal ?

**Comment by lifupan** [comment]
Yes, that's the RAW IP's normal request. 

Fupan

**Comment by lifupan** [comment]
Did you have any concerns on this issue?

**Comment by aaronadlink** [comment]
No.
thanks
