### ISSUE TITLE
Build issues on Ubuntu 17.04 build host

### ISSUE THREAD

**Issue by masselstine** [WindRiver-OpenSourceLabs/wr-core#54]
We are seeing build failures on Ubuntu 17.04 builds hosts related to Pseudo while building the initramfs:
---
No real function for mknod: /home/wrlbuild/pulsar/wr-core/build-intel-x86/tmp/sysroots/x86_64-linux/usr/bin/../lib/pseudo/lib64/libpseudo.so: undefined symbol: mknod
No real function for mknodat: /home/wrlbuild/pulsar/wr-core/build-intel-x86/tmp/sysroots/x86_64-linux/usr/bin/../lib/pseudo/lib64/libpseudo.so: undefined symbol: mknodat
No real function for mknod: /home/wrlbuild/pulsar/wr-core/build-intel-x86/tmp/sysroots/x86_64-linux/usr/bin/../lib/pseudo/lib64/libpseudo.so: undefined symbol: mknod
---

This appears to be fixed upstream already via openembedded-core commit 21c38a091c4a1917f62a942c4751b0fd11dce340 [pseudo: Work around issues with glibc 2.24]. Back-porting this change seems to resolve the issue.

**Comment by jwessel** [comment]
Fixed by commit: 28991472deded4c5d5b27e888a51abf6aa1d8ac3
