### ISSUE TITLE
Build WARNING

### ISSUE THREAD

**Issue by masselstine** [WindRiver-OpenSourceLabs/wr-core#55]
I am seeing this warning when completing a build

WARNING: essential-cfg-mgr: the directory ${WORKDIR}/${BP} (/usr/work/rad/pulsar/wr-core/build-intel-x86/tmp/work/core2-64-wrs-linux/essential-cfg-mgr/1.0-r0/essential-cfg-mgr-1.0) pointed to by the S variable doesn't exist - please set S within the recipe to point to where the source has been unpacked to

Since the package doesn't have a SRC_URI with a git repo or tarball the default for 'S' is never created. We need to update the recipe to have 'S = "${WORKDIR}"' and we should be clear of this warning.

**Comment by masselstine** [comment]
Patch sent.

**Comment by jwessel** [comment]
fixed by commit 0de16686564bd42a6f4f0e7f4c45d604f29d773c
