### ISSUE TITLE
How to use IMA in intel apollo lake secure full feature ?

### ISSUE THREAD

**Issue by aaronadlink** [WindRiver-OpenSourceLabs/wr-core#58]
How to sign ima key when i direct added new files , folders or container in system ?

**Comment by jiazhang0** [comment]
On your build host, run the command: evmctl ima_sign --rsa --hashalgo sha256 --key <path_to_priv_key>. If your project is not configured to use the user key, the default sample key will be used for IMA signing, which means the <path_to_priv_key> points to $project/wr-core/layers/meta-secure-env/files/ima_keys/ima_privkey.pem.

**Comment by jiazhang0** [comment]
To sign a folder, use -r option. See the help info of evmctl.

**Comment by aaronadlink** [comment]
Hi, jiazhang0

thank you for your information

**Comment by jiazhang0** [comment]
@aaronadlink If this problem is gone, plz close this issue. Thanks.
