### ISSUE TITLE
Increase  partition size

### ISSUE THREAD

**Issue by vanidesai** [WindRiver-OpenSourceLabs/wr-core#6]
Hi,

I want to increase partition size of the container. I have looked into cubit-installer script and found that partition table is read from fdisk-4-parition-layout.txt. This file is cryptic. Can you share steps to increase partition size for essential container and gateway container?

Thanks,
Vani

**Comment by jwessel** [comment]
The layout table there is the input to fdisk. 

Depending on if you are creating an image which you are using "dd" or using this as an installer will depend on how it is used.  You can change the TARGET_DISK_SIZE in one of the install templates to increase the overall size of the image which is written out in the dd style install.

**Comment by vanidesai** [comment]
I could increase image size by adding disk-size parameter to cubeit script

sudo ../overc-installer/sbin/cubeit --force --config `pwd`/../install_templates/MinnowBoardMax/MinnowBoardMax-live.sh --disk-size 20G --target-config MinnowBoardMax-live.sh --artifacts  `pwd`/tmp/deploy/images/intel-corei7-64 pulsar7-minnowboardmax.img

**Comment by masselstine** [comment]
Doesn't look like this issue requires any more followup so closing. If there is still something to do here feel free to open a new issue.
