### ISSUE TITLE
UART1 and UART2 output fails

### ISSUE THREAD

**Issue by michaesc** [WindRiver-OpenSourceLabs/wr-core#61]
Hardware: MinnowBoard Turbot
OS: wr-core Pulsar8 branch (build as usual with bitbake)
Container tested: essential (dom0, dom1, cube-gw, cube-server, and cube-desktop not booted)
Connector diagram followed: https://minnowboard.org/board-viewer

$ ls /dev/ttyS*
ttyS0    ttyS1    ttyS2   ttyS3

Attaching a FTDI (six wire) cable to the MinnowBoard's TTL serial connector U4 'UART0' works properly, revealing a login prompt as defined in /etc/login.defs.)

PROBLEM

Attaching the same FTDI cable (via wire jumpers only on black-ground, yellow-receive, and orange-transmit) to the UART1 pins does not produce a login prompt, even after trying to connect in the same manner as with the successful UART0 test, testing with both 115200 and 2764800 bps:

ubuntu$ screen /dev/ttyUSB0 115200
ubuntu$ cu -l /dev/ttyUSB0 115200

EXPECTED OUTCOME

After reading /dev/login.defs I expect an agetty(1) login prompt on all UART interfaces of the MinnowBoard.

QUESTIONS

The UART0 is a legacy serial interface on the MinnowBoard while UART1 and UART2 are high speed PCI based (or something like that) so is it required to load a kernel module or some driver to use them?

I've tried testing UART1 from within Wind River Pulsar8 essential with:

$ while true; do echo `date` >/dev/ttyS1 && sleep 2; done &
$ cat /dev/ttyS1
...while physically bridging the RX and TX pins of UART1 (like with a paperclip.)

Is there some good validation test to determine if UART1 is usable at all?

NOTES

Keep in mind, I'm using the diagram and pin assignments according to:

https://minnowboard.org/board-viewer

REQUEST

Please help solve this problem of getting no output on UART1, thanks.

**Comment by michaesc** [comment]
Nobody offered help, so I figured it out on my own after trial and error for many hours. In any case, the current Wind River Pulsar8 remains flawed, probably indicating it's not ready yet for applications requiring stable UART features.

**Comment by jwessel** [comment]
As far as I know the UART works on the Minnow Board.  It is worth noting that only the UART0 is hooked up for output from the UEFI rom redirection by default.  I used a MinowBoard Max and plugged a ttl -> USB converter into the UART 1 receive/transmit as well as the ground. 

You can modify the image before you boot to change the screen-getty to start on a different port, or do it from the booted device if you can access the HDMI.   From the HDMI you would login and run:

cube-console dom0
cube-console cube-essential
systemctl disable screen-getty@ttyS0
systemctl enable screen-getty@ttyS1

Or you can do the following if you mount the second partition:
```
cd MOUNTED_FIRST_PARTITION
rm -f etc/systemd/system/getty.target.wants/screen-getty@ttyS0.service
ln -s /lib/systemd/system/screen-getty@.service etc/systemd/system/getty.target.wants/screen-getty@ttyS1.service
```
