### ISSUE TITLE
Failed to clone master-oci branch

### ISSUE THREAD

**Issue by yunguowei** [WindRiver-OpenSourceLabs/wr-core#79]
See error below:

Fetched in submodule path 'layers/meta-openembedded', but it did not contain 5add7871e694d9c44ff04c647c778c27c2172c60. Direct fetching of that commit failed

**Comment by lifupan** [comment]
this issue has been fixed by this commit: 933473123548809c20292a95ce1fb365ff74c554
So close it.

Fupan
