### ISSUE TITLE
Not seeing wifi network on AGATE

### ISSUE THREAD

**Issue by edhaynes** [WindRiver-OpenSourceLabs/wr-core#8]
I'm following the directions for the LS1021A=IOT Agate.  All goes fine, boot and enter console through HDMI and install the rtlswitch and reboot.  I don't see the pulsar_xxxx wifi network with any of my devices however.  There is a br_lan 192.168.1.1 network interface but not picking up wireless signal anywhere from either dell laptop or apple phone.

**Comment by lifupan** [comment]
What's the wireless network card you used? 
Generally the Intel's 7260 wifi card should work.

Fupan

**Comment by edhaynes** [comment]
My mistake - my unit doesn't have Wifi card installed.  Will close this one!
