### ISSUE TITLE
Build fail due to Fetcher failure for package source

### ISSUE THREAD

**Issue by jackychen614615** [WindRiver-OpenSourceLabs/wr-core#81]
Hello 

Below is the error when build the pulsar by below step

bitbake cube-desktop cube-dom0 cube-essential cube-gw

NOTE: Executing RunQueue Tasks
WARNING: Failed to fetch URL http://neil.brown.name/wiggle/wiggle-1.0.tar.gz, attempting MIRRORS if available
ERROR: Fetcher failure: Fetch command failed with exit code 4, output:
failed: No route to host.

ERROR: Function failed: Fetcher failure for URL: 'http://neil.brown.name/wiggle/wiggle-1.0.tar.gz'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /home/jacky/pulsar/wr-core/build-intel-apollolake/tmp/work/core2-64-wrs-linux/wiggle/1.0-r1/temp/log.do_fetch.17567
ERROR: Task 4389 (/home/jacky/pulsar/wr-core/layers/meta-overc/meta-cube/recipes-devtools/wiggle/wiggle_1.0.bb, do_fetch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 6223 tasks of which 6215 didn't need to be rerun and 1 failed.
Waiting for 0 running tasks to finish:

Summary: 1 task failed:
  /home/jacky/pulsar/wr-core/layers/meta-overc/meta-cube/recipes-devtools/wiggle/wiggle_1.0.bb, do_fetch
Summary: There were 2 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.

**Comment by zeddii** [comment]
This is already fixed on master-oci. We can cherry pick it as required.

Bruce

**Comment by zeddii** [comment]
https://github.com/WindRiver-OpenSourceLabs/meta-overc/commit/53709d710ced39597cf928127a1440f4e8b5ba1c

**Comment by jwessel** [comment]
Thanks!  merged and closed out.
