### ISSUE TITLE
Where is the compliance envelope?

### ISSUE THREAD

**Issue by PaulKushner** [WindRiver-OpenSourceLabs/wr-core#83]
According to Pulsar-Linux-Product-Overview.pdf there is a product compliance envelope described as:
"
The product comes with a compliance envelope—a zipped archive that contains the
following:
• All required licensing data
• Source code legal notices
• Export cryptography information associated with the OSS used to construct the product
"

How do I find this archive in the source code (i.e. not on the target)?

Thanks

**Comment by jwessel** [comment]
The archive in question is distributed as a part of the artifacts directory provided with an official binary of Pulsar Linux from Wind River.  It is generated as a product of the build process when the local.conf.

Please reference the following Yocto Project documentation for information if you are interested in generating such reports:

https://www.yoctoproject.org/docs/2.1/dev-manual/dev-manual.html#maintaining-open-source-license-compliance-during-your-products-lifecycle
