### ISSUE TITLE
ovmf build fails when PARALLEL_MAKE is set

### ISSUE THREAD

**Issue by dbalashenka** [WindRiver-OpenSourceLabs/wr-core#86]
Hello,

On the pulsar-x branch, when PARALLEL_MAKE is set (PARALLEL_MAKE = "-j4"), ovmf fails to build with the following output:
| Running edk2 build for OvmfPkgX64
| Usage: build.exe [options] [all|fds|genc|genmake|clean|cleanall|cleanlib|modules|libraries|run]
| 
| build.exe: error: Option -n only allows one instance in command line!
| WARNING: /mnt/builds/dzimitry-builds/ic_edge-build-apl-pulsar-x/build-intel-x86/tmp/work/core2-64-wrs-linux/ovmf/git-r0/temp/run.do_compile.123619:1 exit 2 from '/mnt/builds/dzimitry-builds/ic_edge-build-apl-pulsar-x/build-intel-x86/tmp
/work/core2-64-wrs-linux/ovmf/git-r0/git/OvmfPkg/build.sh $PARALLEL_JOBS -a $OVMF_ARCH -b RELEASE -t ${FIXED_GCCVER}'

It seems, that the issue is coming from the ovmf_git.bb recipe, where PARALLEL_MAKE is used.

Thanks,
Dzmitry

**Comment by jwessel** [comment]
Does the package build when you build it individually?  e.g. 

bitbake -c cleansstate ovmf 
bitbake ovmf 

I have not been able to get it to fail to build and wonder if it is a race condition of some kind.

**Comment by dbalashenka** [comment]
It failed with the same error. But when I went to the ovmf recipe and hardcoded PARALLEL_JOBS="-j 4" and that worked:
#PARALLEL_JOBS="${@ '${PARALLEL_MAKE}'.replace('-j', '-n')}"
PARALLEL_JOBS="-j 4"

I'm not sure about the -j option, though. May be it is about not proper use of -n option (multiple instance, as the error log suggest). I did not go further.

**Comment by jwessel** [comment]
Which host OS are you using for the build?  

Using Ubuntu 16.04 didn't seem to have the problem. 

In my case bitbake -e ovmf |grep ^PARALLEL_MAKE
PARALLEL_MAKE="-j 128"

It isn't clear that it is a parsing problem or a race condition.  I don't know if the compile log will have useful information in it or not.  Sometimes you have to run with the "bitbake -v -v -v ovmf" in order for it to emit what it is doing with the shell script part. 

I also tried setting the PARALLEL_MAKE="-j 4" and it built ok too.

**Comment by dbalashenka** [comment]
The OS info (from /etc/os-release): 16.04.2 LTS (Xenial Xerus)

I will try to reproduce it and will come back with more info

**Comment by dbalashenka** [comment]
Ok, the problem arrives when there is no space in '-j4'. Then it will translate into: 
OvmfPkg/build.sh **-n4**  -a IA32 -b RELEASE -t GCC5
which failes, but
OvmfPkg/build.sh **-n 4**  -a IA32 -b RELEASE -t GCC5
compiles with no issues

**Comment by jwessel** [comment]
Thanks for the clarification.  I assume you will probably close the case then?

The reference template in the oe-core might not say it directly but the space is required because some other packges also interpret the -j string.

Specifically Line 19:
https://github.com/WindRiver-OpenSourceLabs/oe-core/blob/master/meta/conf/local.conf.sample.extended

**Comment by dbalashenka** [comment]
Ok, we will manage it on our side. Thank you for helping with it.

Just my opinion... -j4 is also a valid option, and ovmf probably the only package, which does not like it. We have been using it like this in our builds all the time. If not fixed, eventually someone else will run into it. Alternative solution that I would consider is to tweak a line "PARALLEL_JOBS="${@ '${PARALLEL_MAKE}'.replace('-j', '-n ')}"". This could be the simplest one, but not ideal as well. Ideally build.sh needs a fix.

**Comment by jwessel** [comment]
It does seem reasonable to send the change you suggested along to the OE community. 

http://lists.openembedded.org/pipermail/openembedded-core/2017-December/145290.html

Thanks for the information!
