### ISSUE TITLE
Unable to access additional containers

### ISSUE THREAD

**Issue by chriscurrym2** [WindRiver-OpenSourceLabs/wr-core#88]
After building a custom kernel, and copying this into the OVERCBOOT partition of my SD Card, I can no longer access any other container than 'cube-essential'. I'm running Pulsar Linux 8.0.0.8 on a MicroZed 7020. The output of dmesg gives these error messages just after systemd sets the hostname to cube-essential:

`[    3.739677] systemd-gpt-auto-generator[76]: Failed to determine block device of root file system: No such file or directory`
`[    3.771340] systemd[72]: /lib/systemd/system-generators/systemd-gpt-auto-generator failed with error code 1.`
`[    3.977634] systemd[1]: serial-getty@ttyPS0.service: Cannot add dependency job, ignoring: Unit serial-getty@ttyPS0.service is masked.`
`[    3.988905] systemd[1]: openvswitch.service: Cannot add dependency job, ignoring: Unit openvswitch.service failed to load: No such file or directory.`

If I switch back to an older kernel version with fewer modifications all of the LXC containers load correctly. Any suggestions about what might have caused this would be greatly appreciated.

**Comment by masselstine** [comment]
How did you configure your custom kernel? Did you generate an updated initramfs? The information you provided is not enough for us to be able to assist.

**Comment by chriscurrym2** [comment]
Modifications were adding ADC/DAC/GPIO Expander drivers from menuconfig and some minor SPI master patches for our hardware. The process for modifying the kernel was to run the following bitbake commands with a new recipe for our custom kernel that points to a local clone of the git in the SRC_URI.

`$ bitbake linux-yocto-m2 -c kernel_configme -f`
`$ bitbake linux-yocto-m2 -c menuconfig`
`$ bitbake -k linux-yocto-m2`

I also created a custom append recipe that performs the same steps as the WindRiver linux-yocto_4.1.bbappend recipe in the wrlabs-integration layer.  I modified local.conf to use the custom kernel, rebuilt the three containers (cube-essential, cube-dom0, cube-server), then generated an entirely new image of Pulsar Linux with the following:

'$ sudo ../overc-installer/sbin/cubeit --force --config `pwd`/../install_templates/ZedBoard/MicroZed-7020-live.sh --target-config MicroZed-7020-live.sh --artifacts `pwd`/tmp/deploy/images/xilinx-zynq pulsar8-m2.img'

Which I then tested on another SD card and found the same result.

**Comment by masselstine** [comment]
Based on what you are doing with the kernel I would suggest a different approach in that you don't swap in a custom kernel and instead apply your changes on top of linux-yocto.

Create a custom layer with a higher priority than the other layers and copy the kernel bbappend. Then create scc and cfg files to apply the Kconfigs (instead of menuconfig) and use SRC_URI to apply your SPI patches. I think you will find it about the same as far as effort and the benefits will stem from this approach first in that you shouldn't see the issue you are seeing and secondly in easing future builds.

If what you describe above is the extent of your changes than I really do promote this approach.

**Comment by chriscurrym2** [comment]
Thanks for the advice - I'm still fairly new to Yocto, so this is really useful. I have managed to fix the issue with the other containers not loading. I had a scan through the other layers & noticed that there was a bbappend file for linux-yocto in meta-overc/meta-cube which I'd missed, and in this there were .cfg files referring to OpenVSwitch, LXC, etc., so I created a copy of this with my prefix, rebuilt the kernel, copied it to the SD card and everything loads as expected. I agree with you that it's probably best to do the Kconfigs with scc & cfg files. In terms of changing the SRC_URI in the bbappend in a higher priority layer, does this overwrite the SRC_URI provided in the base linux-yocto recipe? I'm unsure of how this mechanism is actually implemented in Bitbake.

**Comment by masselstine** [comment]
Yes you definitely need the configs and patches from the kernel bbappend in meta-overc/meta-cube and this would most definitely would cause some of the issues were seeing.

If you use the bbappend from meta-overc as the starting point for your custom layer you should be OK as far as SRC_URI and such are concerned. You should review the documentation on assignment operators and _append and friends to get comfortable with what you can do without overwriting existing values. You can always do things like 'bitbake virtual/kernel -e' to examine the variables to see that you are getting what you expect.

By the way, ideally you would only require additional kernel modules which you could build as out of tree and thus not have a need to touch the kernel that we 'ship'. But I won't go down that road just now as you are just getting up to speed. At any rate I am going to close this issue as I think we have addressed your initial issue. If anything else comes up don't hesitate to create new issues.
