### ISSUE TITLE
Intel build fails

### ISSUE THREAD

**Issue by edhaynes** [WindRiver-OpenSourceLabs/wr-core#9]
Following build instructions at 
https://github.com/WindRiver-OpenSourceLabs/wr-core/blob/pulsar-7.0/docs/README-intel-x86.TXT
fails with "Error, user requested feature SDL configure was not able to find it"  .  For now I've commented out 
# PACKAGECONFIG_append_pn-qemu-native = " sdl"
# PACKAGECONFIG_append_pn-nativesdk-qemu = " sdl"
# ASSUME_PROVIDED += "libsdl-native"

in local.conf to continue to build.

ERROR: Function failed: do_configure (log file is located at /home/ehaynes/wr-core/build-intel-x86/tmp/work/x86_64-linux/qemu-native/2.1.2-r0/temp/log.do_configure.8106)
ERROR: Logfile of failure stored in: /home/ehaynes/wr-core/build-intel-x86/tmp/work/x86_64-linux/qemu-native/2.1.2-r0/temp/log.do_configure.8106
Log data follows:
| DEBUG: Executing python function sysroot_cleansstate
| DEBUG: Python function sysroot_cleansstate finished
| DEBUG: Executing shell function autotools_preconfigure
| DEBUG: Shell function autotools_preconfigure finished
| DEBUG: Executing python function autotools_copy_aclocals
| DEBUG: Python function autotools_copy_aclocals finished
| DEBUG: Executing shell function do_configure
| 
*_| ERROR: User requested feature sdl
|        configure was not able to find it.
|        Install SDL devel
| *_
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_configure (log file is located at /home/ehaynes/wr-core/build-intel-x86/tmp/work/x86_64-linux/qemu-native/2.1.2-r0/temp/log.do_configure.8106)
ERROR: Task 188 (virtual:native:/home/ehaynes/wr-core/layers/oe-core/meta/recipes-devtools/qemu/qemu_2.1.2.bb, do_configure) failed with exit code '1'
NOTE: Tasks Summary: Attempted 857 tasks of which 0 didn't need to be rerun and 1 failed.
NOTE: Build completion summary:
NOTE:   From shared state: 0
NOTE:   From scratch: 84
Waiting for 0 running tasks to finish:

Summary: 1 task failed:
  virtual:native:/home/ehaynes/wr-core/layers/oe-core/meta/recipes-devtools/qemu/qemu_2.1.2.bb, do_configure
Summary: There were 7 WARNING messages shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

**Comment by masselstine** [comment]
Fixed by https://github.com/WindRiver-OpenSourceLabs/wr-core/commit/11c1be7e5bd98a5b0d0d781278cc2bd5fe1e1f9f
