### ISSUE TITLE
Cant install Petalinux in Ubuntu under Windows 10

### ISSUE THREAD

**Issue by JohnPRed** [WindRiver-OpenSourceLabs/wr-core#92]
/mnt/d/Downloads/petalinux-v2016.2-final-installer.run /opt/pkg
-bash: /mnt/d/Downloads/petalinux-v2016.2-final-installer.run: Cannot allocate memory
Is there a fix for this?
Should I abandon using Ubuntu under windows and go back to Cygwin64?

**Comment by jwessel** [comment]
The wr-core has nothing to do with petalinux.  Perhaps you registered an issue to the wrong location.  The primary official cross build environment should be run in a Docker container on Linux, or a supported Linux host natively.

**Comment by hugoliu2019** [comment]
Please use the command:
bash petalinux-v2016.2-final-installer.run
